export const PuzzleActionTypes = {
  SET_PUZZLE: 'SET_PUZZLE',
  SET_PUZZLE_ARRAY: 'SET_PUZZLE_ARRAY',
  SET_PREVIEW_ARRAY: `SET_PREVIEW_ARRAY`,
  SET_TEMP_ARRAY: 'SET_TEMP_ARRAY',
  SET_PREVIEW_STATE: 'SET_PREVIEW_STATE',
  SET_SWITCHER_STATE: 'SET_SWITCHER_STATE',
  SET_STATE_TO_INIT: 'SET_STATE_TO_INIT'
}